name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: go build -v ./..
      - name: Tests
        run: go test -v ./..
    
  push-docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker
        run: docker build -t rambah/myhello:latest ./
      - run: docker tag rambah/myhello:latest rambah/myhello:$(git rev-parse --short HEAD)
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker image push -a rambah/myhello
  
  trivy:
    name: Trivy Check
    needs: push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker Check
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: rambah/myhello:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          skip-files: "*.go"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      - name: Run Code Check
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: "."
          format: sarif
          output: trivy-results.sarif
          severity: "CRITICAL,HIGH"
      
